# Generated by Django 2.2.10 on 2020-02-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190630_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('KC', 'Key Chain'), ('S', 'Shirt'), ('C', 'Cup'), ('B', 'Bag'), ('D', 'Dictionary'), ('PD', 'Premium Product'), ('M', 'Medal'), ('C', 'Cap'), ('O', 'Other')], max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(max_length=2083, upload_to=''),
        ),
    ]
