# Generated by Django 2.2.10 on 2020-02-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200220_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('KC', 'Key Chain'), ('S', 'Shirt'), ('CU', 'Cup'), ('B', 'Bag'), ('D', 'Dictionary'), ('PD', 'Premium Product'), ('M', 'Medal'), ('CA', 'Cap'), ('O', 'Other')], max_length=2),
        ),
    ]
