# Generated by Django 2.2.10 on 2020-03-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200227_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='count_sold',
            field=models.IntegerField(default=0, verbose_name='count sold'),
        ),
    ]
