# Generated by Django 2.2.10 on 2020-05-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_item_count_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='count_sold',
            field=models.IntegerField(default=0),
        ),
    ]
