# Generated by Django 2.2.10 on 2020-05-31 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200519_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotiDisplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VisitProduct',
            fields=[
                ('sessionid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('visitnum', models.IntegerField()),
                ('productname', models.CharField(max_length=100)),
                ('productcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Category')),
            ],
        ),
        migrations.CreateModel(
            name='DisplayAds',
            fields=[
                ('sessionid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Item')),
            ],
        ),
    ]
