# Generated by Django 2.2.10 on 2020-06-01 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_displayads_notidisplay_visitproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VisitProduct',
        ),
    ]
