# Generated by Django 2.2.10 on 2020-06-01 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_delete_visitproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionid', models.CharField(max_length=100)),
                ('visitnum', models.IntegerField()),
                ('productname', models.CharField(max_length=100)),
                ('productcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Category')),
            ],
        ),
    ]
