# Generated by Django 2.2.10 on 2020-06-01 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_visitproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DisplayAds',
        ),
    ]
